[package]
name = "oplog"
version = "0.1.0"
authors = ["Paul Mucur <mudge@mudge.name>"]
repository = "https://github.com/mudge/oplog"
readme = "README.md"
license = "MIT"

[dependencies]
bson = "^0.3.0"
mongodb = "^0.1.8"
chrono = "^0.2.0"
